### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by cicklolwut** [fafaraway/andromeda#1]
Left a comment on wowinterface page, but unsure if you keep up with it. Is there an updated version of the options folder? Having some trouble getting any changes to stick. Also, with a fresh install it appears that target buffs/debuffs aren't showing up on fresh install. Apologies if this is the wrong place to report this, just thought I'd bring my issue to attention.

**Comment by cicklolwut** [comment]
Alright correction, so I see that player buffs are showing, but debuffs i put on my target are not. It appears upon entering combat (a duel in this instance), the target player's buffs disappear, and continue to not show inflicted debuffs

**Comment by fafaraway** [comment]
everything's broken, need more time to fix them 😢 

I'm still working on options panel, there will be a proper release before BfA live 🥂 

if you find any bug or error, just post it here 👍

**Comment by cicklolwut** [comment]
Okay, cool. Just glad to know it's not just me. If you need help testing, just let me know. I'm no script pro but I'm literate enough to kinda tell what's going on.
