### ISSUE TITLE
Extra actions buttom in raid gone

### ISSUE THREAD

**Issue by Boniewow** [fafaraway/andromeda#104]
Did the boss Eye of the jailer. First time when you use the change the button was there sec time is was gone, Ofc i died :=)) Even when it was working it is wery small any way to make it bigger ? it is kind of important in raid!

**Comment by fafaraway** [comment]
Did heroic Eye of the Jailer this week, extra action button works fine.
Please disable other addons to confirm whether the problem is caused by FreeUI.

**Comment by Boniewow** [comment]
I realy hade no addon except weakauras and bigwigs, details.

**Comment by fafaraway** [comment]
bind it with a shortcut key, there is no need to manually click the button

**Comment by Boniewow** [comment]
Yeh already using it. the problem it is a same icon as on other
dungeon-quest boss fight and you cant se so easy when it is ready to use.
just wanted to report the bug :=)

**Comment by fafaraway** [comment]
Did heroic Eye of the Jailer again this weekend and confirmed that the extra action button is working normally.
Close this issue for now unless you find more relevant clues ;)
