### ISSUE TITLE
Error by choosing a Profession

### ISSUE THREAD

**Issue by Nithaiel** [fafaraway/andromeda#105]
1/2

Message: Interface\AddOns\FreeUI\modules\tooltip\item.lua:15: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Thu Aug 12 22:56:21 2021
Count: 24
Stack: Interface\AddOns\FreeUI\modules\tooltip\item.lua:15: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: ?
[string "@Interface\AddOns\FreeUI\modules\tooltip\item.lua"]:15: in function <Interface\AddOns\FreeUI\modules\tooltip\item.lua:11>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals: (*temporary) = nil

2/2

Message: Interface\AddOns\FreeUI\modules\tooltip\item.lua:15: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Thu Aug 12 22:56:13 2021
Count: 31
Stack: Interface\AddOns\FreeUI\modules\tooltip\item.lua:15: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: ?
[string "@Interface\AddOns\FreeUI\modules\tooltip\item.lua"]:15: in function <Interface\AddOns\FreeUI\modules\tooltip\item.lua:11>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?

Locals: (*temporary) = nil

Hi,
thats my Problem if I´m choosing A profession with a new Character. Can you do something with this Information that I send you?

Greetings

**Comment by fafaraway** [comment]
will be fixed in next release, thanks for your feedback ;)

**Comment by fafaraway** [comment]
try 9.5.2
