### ISSUE TITLE
9.5版本交易依然报错

### ISSUE THREAD

**Issue by juniorsang** [fafaraway/andromeda#111]
Message: Interface\FrameXML\ContainerFrame.lua:1607: attempt to index local 'frame' (a boolean value)
Time: Sun Sep 19 12:20:46 2021
Count: 2
Stack: Interface\FrameXML\ContainerFrame.lua:1607: attempt to index local 'frame' (a boolean value)
[string "@Interface\FrameXML\ContainerFrame.lua"]:1607: in function <Interface\FrameXML\ContainerFrame.lua:1593>
[string "@Interface\AddOns\FreeUI\modules\inventory\inventory.lua"]:794: in function `func'
[string "@Interface\AddOns\FreeUI\init.lua"]:84: in function <Interface\AddOns\FreeUI\init.lua:79>

Locals: frame = true
forceUpdate = nil
(*temporary) = nil
(*temporary) = true
(*temporary) = 4
(*temporary) = 1
(*temporary) = 4
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a boolean value)"
FRAME_THAT_OPENED_BAGS = nil

**Comment by Humwq** [comment]
这个有点眼熟。。。。
你排查下 其他插件  看看是否冲突了 

原则上，单独只运行FreeUI没报错  就不是FreeUI的问题   
如果某2个插件冲突了，但是单独开又都没事，那么两个插件的作者都不会管，，，，只能放弃某一个了

**Comment by fafaraway** [comment]
更新到9.5.2
