### ISSUE TITLE
9.5.8-alpha-1 国服9.15有2个报错

### ISSUE THREAD

**Issue by Humwq** [fafaraway/andromeda#116]
5x FreeUI\modules\map\minimap.lua:699: attempt to index field 'backdrop' (a nil value)
[string "@FreeUI\modules\map\minimap.lua"]:699: in function `UpdateMinimapScale'
[string "@FreeUI\modules\map\minimap.lua"]:728: in function `GetMinimapShape'
[string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:126: in function <BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:121>
[string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:275: in function <BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:216>
[string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:321: in function `Register'
[string "@BugSack\ldb.lua"]:62: in function <BugSack\ldb.lua:58>

Locals:
self = <table> {
 Minimap_OnMouseWheel = <function> defined @FreeUI\modules\map\minimap.lua:647
 CreateZoneText = <function> defined @FreeUI\modules\map\minimap.lua:525
 CreateMailButton = <function> defined @FreeUI\modules\map\minimap.lua:341
 CreateCalendar = <function> defined @FreeUI\modules\map\minimap.lua:352
 CreateGarrisonButton = <function> defined @FreeUI\modules\map\minimap.lua:505
 WhoPings = <function> defined @FreeUI\modules\map\minimap.lua:600
 MouseFunc = <function> defined @FreeUI\modules\map\minimap.lua:669
 Minimap_OnMouseUp = <function> defined @FreeUI\modules\map\minimap.lua:655
 UpdateDifficultyFlag = <function> defined @FreeUI\modules\map\minimap.lua:410
 CreateQueueStatusButton = <function> defined @FreeUI\modules\map\minimap.lua:563
 OnLogin = <function> defined @FreeUI\modules\map\minimap.lua:734
 HideInCombat = <function> defined @FreeUI\modules\map\minimap.lua:705
 name = "Minimap"
 UpdateMinimapScale = <function> defined @FreeUI\modules\map\minimap.lua:696
 SetupHybridMinimap = <function> defined @FreeUI\modules\map\minimap.lua:682
 HybridMinimapOnLoad = <function> defined @FreeUI\modules\map\minimap.lua:675
 ReskinMinimap = <function> defined @FreeUI\modules\map\minimap.lua:282
 CreateDifficultyFlag = <function> defined @FreeUI\modules\map\minimap.lua:485
}
scale = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = <userdata>
(*temporary) = "attempt to index field 'backdrop' (a nil value)"
C = <table> {
 LineString = "|cff7f7f7f---------------"
 Assets = <table> {
 }
 IsRetail = true
 MyName = "Dthird"
 Frames = <table> {
 }
 CharacterSettings = <table> {
 }
 TexCoord = <table> {
 }
 PartyPetFlags = 4370
 MyRealm = "灰谷"
 IsInMyGroup = <function> defined @FreeUI\core\constants.lua:253
 GreenColor = "|cff20ff20"
 NPShowPowerUnitsList = <table> {
 }
 YellowColor = "|cffffff00"
 ServerID = 954
 RaidPetFlags = 4372
 MyGuid = "Player-954-04E8E604"
 ClassColors = <table> {
 }
 MyFaction = "联盟"
 QualityColors = <table> {
 }
 RedColor = "|cffff2020"
 WhiteColor = "|cffffffff"
 AccountSettings = <table> {
 }
 IsNewPatch = false
 IsHighRes = false
 MyClass = "DRUID"
 OrangeColor = "|cffff7f3f"
 ClassList = <table> {
 }
 PartyBuffsList = <table> {
 }
 BadBoys = <table> {
 }
 Themes = <table> {
 }
 Mult = 1
 MaxLevel = 60
 ColoredAddonName = "|cffe67e22F|cffe67e22r|cffe67e22e|cffeb984ee|cfff5cba7U|cffffffffI"
 TrashUnits = <table> {
 }
 NPMajorSpellsList = <table> {
 }
 MyColor = "|cffe67e21"
 BlizzThemes = <table> {
 }
 MyRace = "NightElf"
 MyLevel = 60
 AuraWhiteList = <table> {
 }
 GreyColor = "|cff7f7f7f"
 IsMyPet = <function> defined @FreeUI\core\constants.lua:247
 IsDeveloper = false
 AddonThemes = <table> {
 }
 BloodlustList = <table> {
 }
 PartySpellsList = <table> {
 }
 DB = <table> {
 }
 b = 0.133333
 g = 0.494118
 UIGap = 33
 InfoColor = "|cffe9c55d"
 r = 0.901961
 PartyDebuffsBlackList = <table> {
 }
 PartySpellsDB = <table> {
 }
 TalentCDFixList = <table> {
 }
 AuraBlackList = <table> {
 }
 MyRole = "Caster"
 ScreenWidth = 1920
 IsLowRes = false
 ShowTargetNPCs = <table> {
 }
 CornerSpellsList = <table> {
 }
 BlueColor = "|cff82c5ff"
 AddonName = "FreeUI"
 MyGUID = "Player-954-04E8E604"
 NPSpecialUnitsList = <table> {
 }
 AssetsPath = "FreeUI\assets\"
 AddonVersion = "9.5.8-alpha-1"
 ScreenHeight = 1200
 IsMedRes = true
 AnnounceableSpellsList = <table> {
 }
 MyFullName = "Dthird-灰谷"
 PurpleColor = "|cffa571df"
}
map = Minimap {
 0 = <userdata>
 timer = 0
}

**Comment by Humwq** [comment]
64x FreeUI\modules\misc\friends-list.lua:212: attempt to call method 'Point' (a nil value)
[string "@FreeUI\modules\misc\friends-list.lua"]:212: in function <FreeUI\modules\misc\friends-list.lua:78>
[string "=[C]"]: in function `FriendsFrame_UpdateFriendButton'
[string "@FrameXML\FriendsFrame.lua"]:1282: in function <FrameXML\FriendsFrame.lua:1265>
[string "=[C]"]: in function `FriendsFrame_UpdateFriends'
[string "@FrameXML\FriendsFrame.lua"]:650: in function `FriendsList_Update'
[string "@FrameXML\FriendsFrame.lua"]:1261: in function `FriendsFrame_CheckBattlenetStatus'
[string "@FrameXML\FriendsFrame.lua"]:941: in function `FriendsFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
button = FriendsListFrameScrollFrameButton1 {
 0 = <userdata>
 OnEnter = <function> defined @FrameXML\FriendsFrame.lua:1891
 index = 1
 buttonType = 2
 travelPassButton = FriendsListFrameScrollFrameButton1TravelPassButton {
 }
 status = FriendsListFrameScrollFrameButton1Status {
 }
 background = FriendsListFrameScrollFrameButton1Background {
 }
 OnClick = <function> defined @FrameXML\FriendsFrame.lua:2072
 OnLoad = <function> defined @FrameXML\FriendsFrame.lua:1879
 id = 1
 OnLeave = <function> defined @FrameXML\FriendsFrame.lua:2067
 highlight = <unnamed> {
 }
 name = FriendsListFrameScrollFrameButton1Name {
 }
 bg = <unnamed> {
 }
 summonButton = FriendsListFrameScrollFrameButton1SummonButton {
 }
 info = FriendsListFrameScrollFrameButton1Info {
 }
 Favorite = <unnamed> {
 }
 gameIcon = FriendsListFrameScrollFrameButton1GameIcon {
 }
}
game = ""
realID = "|Kq33|k"
name = nil
server = nil
class = nil
area = nil
level = nil
status = "Offline"
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "LEFT"
(*temporary) = FriendsListFrameScrollFrameButton1Name {
 0 = <userdata>
}
(*temporary) = "LEFT"
(*temporary) = 40.000004
(*temporary) = 0
(*temporary) = "attempt to call method 'Point' (a nil value)"
WOW_PROJECT_CLASSIC_TBC = 5
statusIcons = <table> {
 DND = "FriendsFrame\StatusIcon-DnD"
 Online = "FriendsFrame\StatusIcon-Online"
 Offline = "FriendsFrame\StatusIcon-Offline"
 AFK = "FriendsFrame\StatusIcon-Away"
}
F = <table> {
 GetScreenQuadrant = <function> defined @FreeUI\core\functions.lua:211
 CreateGlowFrame = <function> defined @FreeUI\core\functions.lua:645
 ReskinDropDown = <function> defined @FreeUI\core\functions.lua:1239
 Minimap = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @FreeUI\libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 SecureHook = <function> defined @FreeUI\libs\Ace3\AceHook-3.0\AceHook-3.0.lua:336
 Theme = <table> {
 }
 ScanTip = FreeUI_ScanTooltip {
 }
 SpeedAnimationGroup = <function> defined @FreeUI\core\animation.lua:672
 CopyTable = <function> defined @FreeUI\core\functions.lua:299
 SetDefaultModulePrototype = <function> defined @FreeUI\libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 MultiCheck = <function> defined @FreeUI\core\functions.lua:14
 ReskinNavBar = <function> defined @FreeUI\core\functions.lua:1378
 IsEnabled = <function> defined @FreeUI\libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 InspectItemInfo = <function> defined @FreeUI\core\functions.lua:2427
 ScheduleTimer = <function> defined @FreeUI\libs\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 CreateColorSwatch = <function> defined @FreeUI\core\functions.lua:2027
 RegisterModule = <function> defined @FreeUI\init.lua:160
 CreateAndUpdateBarTicks = <function> defined @FreeUI\core\functions.lua:1808
 RegisterMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @BugSack\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 UnitColor = <function> defined @FreeUI\core\functions.lua:413
 Dummy = <function> defined @FreeUI\core\functions.lua:10
 WaitFrame = FreeUI_WaitFrame {
 }
 FramesOverlap = <function> defined @FreeUI\core\functions.lua:189
 ShortenString = <function> defined @FreeUI\core\functions.lua:558
 SetEnabledState = <function> defined @FreeUI\libs\Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @FreeUI\libs\Ace3\AceHook-3.0\AceHook-3.0.lua:274
 HelpInfoAcknowledge = <function> defined @FreeUI\core\functions.lua:6
 GUI = <table> {
 }
 FlashLoopFinished = <function> defined @FreeUI\core

**Comment by Humwq** [comment]
另外，现在还能设置字体吗？
\modules\blizzard\fonts.lua 里，没有以前的设置项了

**Comment by fafaraway** [comment]
在 `core\constants.lua` 这个文件的127行

**Comment by fafaraway** [comment]
> 5x FreeUI\modules\map\minimap.lua:699: attempt to index field 'backdrop' (a nil value) [string "@FreeUI\modules\map\minimap.lua"]:699: in function `UpdateMinimapScale' [string "@FreeUI\modules\map\minimap.lua"]:728: in function `GetMinimapShape' [string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:126: in function <BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:121> [string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:275: in function <BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:216> [string "@BugSack\Libs\LibDBIcon-1.0\LibDBIcon-1.0-44.lua"]:321: in function `Register' [string "@BugSack\ldb.lua"]:62: in function <BugSack\ldb.lua:58>
> 
> Locals: self =
> 
> {
> Minimap_OnMouseWheel = defined @FreeUI\modules\map\minimap.lua:647
> CreateZoneText = defined @FreeUI\modules\map\minimap.lua:525
> CreateMailButton = defined @FreeUI\modules\map\minimap.lua:341
> CreateCalendar = defined @FreeUI\modules\map\minimap.lua:352
> CreateGarrisonButton = defined @FreeUI\modules\map\minimap.lua:505
> WhoPings = defined @FreeUI\modules\map\minimap.lua:600
> MouseFunc = defined @FreeUI\modules\map\minimap.lua:669
> Minimap_OnMouseUp = defined @FreeUI\modules\map\minimap.lua:655
> UpdateDifficultyFlag = defined @FreeUI\modules\map\minimap.lua:410
> CreateQueueStatusButton = defined @FreeUI\modules\map\minimap.lua:563
> OnLogin = defined @FreeUI\modules\map\minimap.lua:734
> HideInCombat = defined @FreeUI\modules\map\minimap.lua:705
> name = "Minimap"
> UpdateMinimapScale = defined @FreeUI\modules\map\minimap.lua:696
> SetupHybridMinimap = defined @FreeUI\modules\map\minimap.lua:682
> HybridMinimapOnLoad = defined @FreeUI\modules\map\minimap.lua:675
> ReskinMinimap = defined @FreeUI\modules\map\minimap.lua:282
> CreateDifficultyFlag = defined @FreeUI\modules\map\minimap.lua:485
> }
> scale = 1
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = 1
> (*temporary) =
> (*temporary) = "attempt to index field 'backdrop' (a nil value)"
> C =
> {
> LineString = "|cff7f7f7f---------------"
> Assets =
> {
> }
> IsRetail = true
> MyName = "Dthird"
> Frames =
> {
> }
> CharacterSettings =
> {
> }
> TexCoord =
> {
> }
> PartyPetFlags = 4370
> MyRealm = "灰谷"
> IsInMyGroup = defined @FreeUI\core\constants.lua:253
> GreenColor = "|cff20ff20"
> NPShowPowerUnitsList =
> {
> }
> YellowColor = "|cffffff00"
> ServerID = 954
> RaidPetFlags = 4372
> MyGuid = "Player-954-04E8E604"
> ClassColors =
> {
> }
> MyFaction = "联盟"
> QualityColors =
> {
> }
> RedColor = "|cffff2020"
> WhiteColor = "|cffffffff"
> AccountSettings =
> {
> }
> IsNewPatch = false
> IsHighRes = false
> MyClass = "DRUID"
> OrangeColor = "|cffff7f3f"
> ClassList =
> {
> }
> PartyBuffsList =
> {
> }
> BadBoys =
> {
> }
> Themes =
> {
> }
> Mult = 1
> MaxLevel = 60
> ColoredAddonName = "|cffe67e22F|cffe67e22r|cffe67e22e|cffeb984ee|cfff5cba7U|cffffffffI"
> TrashUnits =
> {
> }
> NPMajorSpellsList =
> {
> }
> MyColor = "|cffe67e21"
> BlizzThemes =
> {
> }
> MyRace = "NightElf"
> MyLevel = 60
> AuraWhiteList =
> {
> }
> GreyColor = "|cff7f7f7f"
> IsMyPet = defined @FreeUI\core\constants.lua:247
> IsDeveloper = false
> AddonThemes =
> {
> }
> BloodlustList =
> {
> }
> PartySpellsList =
> {
> }
> DB =
> {
> }
> b = 0.133333
> g = 0.494118
> UIGap = 33
> InfoColor = "|cffe9c55d"
> r = 0.901961
> PartyDebuffsBlackList =
> {
> }
> PartySpellsDB =
> {
> }
> TalentCDFixList =
> {
> }
> AuraBlackList =
> {
> }
> MyRole = "Caster"
> ScreenWidth = 1920
> IsLowRes = false
> ShowTargetNPCs =
> {
> }
> CornerSpellsList =
> {
> }
> BlueColor = "|cff82c5ff"
> AddonName = "FreeUI"
> MyGUID = "Player-954-04E8E604"
> NPSpecialUnitsList =
> {
> }
> AssetsPath = "FreeUI\assets"
> AddonVersion = "9.5.8-alpha-1"
> ScreenHeight = 1200
> IsMedRes = true
> AnnounceableSpellsList =
> {
> }
> MyFullName = "Dthird-灰谷"
> PurpleColor = "|cffa571df"
> }
> map = Minimap {
> 0 =
> timer = 0
> }

无法重现，什么情况下遇到的？

**Comment by Humwq** [comment]
就打开游戏 进去就有
清除错误后 /RL 也有   这2个错误很固定

我试了下 只加载FreeUI和错误收集的插件(BugSack+!BugGrabber)  也是一样结果
Interface下 还有个图标美化的CleanIcons-MechagnomeEdition-9.1.5.40906-V2-1  这个应该不影响吧

**Comment by Humwq** [comment]
8x FreeUI\modules\misc\friends-list.lua:212: attempt to call method 'Point' (a nil value)
这个是打开O键就刷错误了 

小地图那个站街不动的情况下 暂时没再出现。虫洞传送 过地图读条 回城都没再现。
但是重新进游戏和/RL 2个错误就固定出现了

**Comment by Humwq** [comment]
好友那个错误  我看它在刷一个好友的名字。。。 是因为他是亲密好友嘛？

还真是 我移除了亲密好友  开关O键  就没刷了。。。。亲密好友在线  应该就会刷这个错误
战网好友上线提示  我看见又刷了

**Comment by fafaraway** [comment]
9.5.8-alpha-2 修复了这两个报错。

**Comment by Humwq** [comment]
麦大辛苦了~
新年快乐！虎年大吉！
