### ISSUE TITLE
9.5.8-alpha-2 信息条报错

### ISSUE THREAD

**Issue by Humwq** [fafaraway/andromeda#117]
全新电脑上，全新加载的wow，信息条字体报错。。。
全部是默认  只装了FreeUI和收集错误的插件。。

1x FreeUI\modules\infobar\durability-耐久度.lua:74: <unnamed>:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@FreeUI\modules\infobar\durability-耐久度.lua"]:74: in function <FreeUI\modules\infobar\durability.lua:70>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "装备耐久: |cff00ff00100|r%"

**Comment by Humwq** [comment]
7x FreeUI\modules\infobar\friends-好友.lua:567: <unnamed>:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@FreeUI\modules\infobar\friends-好友.lua"]:567: in function <FreeUI\modules\infobar\friends.lua:559>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "好友: |cff00626628"

**Comment by Humwq** [comment]
4x FreeUI\modules\infobar\guild-公会.lua:347: <unnamed>:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@FreeUI\modules\infobar\guild-公会.lua"]:347: in function <FreeUI\modules\infobar\guild.lua:334>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "公会: |cff0062662"

**Comment by Humwq** [comment]
910x FreeUI\modules\infobar\stats.lua:91: <unnamed>:SetText(): Font not set
[string "=[C]"]: in function `SetText'
[string "@FreeUI\modules\infobar\stats.lua"]:91: in function <FreeUI\modules\infobar\stats.lua:78>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "|cffffffff122|r fps   |cffffffff30|r/|cffffffff33|r ms   |cffffffff21:37|r"

**Comment by fafaraway** [comment]
你的自定义字体路径不正确，报错原因是找不到字体。

**Comment by Humwq** [comment]
就很奇怪 我把字体放在\_retail_\Fonts\下  指定位置为C.Assets.Fonts.Regular = 'Fonts\\regular.ttf'  就报错

字体放在\_retail_\Fonts\FreeUI\  指定C.Assets.Fonts.Regular = 'Fonts\\FreeUI\\regular.ttf'  就没问题。。。

无论如何字体改了 也没报错了  感谢指导
