### ISSUE TITLE
新版本找不到动作条布局了。。。

### ISSUE THREAD

**Issue by Oo-Lucas-oO** [fafaraway/andromeda#118]
Hi麦大~新年好~更新了9.2来看了看，发现你更新了稳定的正式版本，下载以后发现动作条布局无法设置了。三大件都删了，只加载了Freeui.

除了控制台以外有没有代码命令可以调整下布局吗？？😃

PS: Discord 频道的Rick 和 Morty机器人大赞~

🖖

**Comment by fafaraway** [comment]
没有这个功能了，除了第三动作条也就是游戏设置里的右下动作条自动拆分，所有动作条的启用与否全都取决于你自己在游戏界面设置里的设定，FreeUI不再接管这些。
但是FreeUI可以控制动作条按键的大小和显示按键的数量。

**Comment by Oo-Lucas-oO** [comment]
emmm...好哒麦大😆~~

**Comment by Oo-Lucas-oO** [comment]
Désolée….又把这个问题开启了。。。

今天早晨我又看了下你的回复，我觉得应该是我没有表达清楚。

然后我想再麻烦问下就是那个bar3的折叠能不能通过注释掉一部分lua从而取消掉？？。。。

其他复杂的布局其实不太需要，就简单的3*12用起来很顺手。。。半鼠标党。。。😆

谢谢麦大啦～哈哈～🙂

**Comment by fafaraway** [comment]
我下次更新加个禁用bar3拆分的选项。

**Comment by Oo-Lucas-oO** [comment]
感谢麦大~~~😉

🖖

**Comment by fafaraway** [comment]
在控制台里，当bar3的num设为0时，自动拆分，大于0时恢复正常，你可以把num设为12，然后把bar3移动到正常位置，这样就是正常的3*12布局了。

**Comment by Oo-Lucas-oO** [comment]
好的麦大～～晚上我试试看～～～Merci beaucoup~ 😄 

🖖
