### ISSUE TITLE
Unable to show player name on party/raid frames

### ISSUE THREAD

**Issue by jabramek** [fafaraway/andromeda#12]
First of all, awesome that you added an options menu in-game!

So,  I play a healer and I would like to display player names on the party/raid frames. I looked through the code and I found what I thought was the line to fix that ['partyNameAlways'] = false, and I changed it to true. That broke my party frame. Is there a way to fix this issue? Technically, it is not an issue because this is how you intended it to be but I'm sure other healers would appreciate the option to display player names. 

Also, do you plan on adding anymore in-game options like the ability to resize frames or the ability to color player health to classcolor?

**Comment by fafaraway** [comment]
775cbf8b3d774a1e3433405805e9d7dfc1db4058 fixed party/raid frames name 🤣 
you can temporarily use this option `C.unitframe.transMode = false` if you perfer classcoloured health bar, and `C.unitframe.player_width` `C.unitframe.player_height` these options control frames size.
I will add unitframe options into in-game options panel when I have time.

**Comment by jabramek** [comment]
Which line do I place C.unitframe.transMode = false on?

**Comment by fafaraway** [comment]
with new updates, unitframes related options have finished
you can uncheck `transparent mode` to use solid colour mode
