### ISSUE TITLE
Weakaura shows Double Timer

### ISSUE THREAD

**Issue by lwndwsk1** [fafaraway/andromeda#123]
Hello, I'm using the latest version of the UI 9.7.5 and I have a problem with one of my Weakauras. Unfortunately, the cooldown text is displayed twice. If I disable FreeUI then I don't have this. Is there an option for this? I have already deactivated the "Hide Timer Text" checkbox in the Weakaura. Unfortunately without success. I don't use any other addons that could trigger it.

Kind regards,
Franky

![freeui-issue](https://user-images.githubusercontent.com/13572147/163736181-0aa1f302-eeee-420b-bc48-b14f78029416.jpg)

**Comment by fafaraway** [comment]
If you want to use FreeUI's own timer, you need to remove the text "%P" from WeakAuras.
If you want to use WeakAuras' own timer, you need to disable the cooldown timer for WeakAuras in FreeUI's GUI.

**Comment by lwndwsk1** [comment]
"Ignore WeakAuras" was the Option.. Thanks for the quick response.. Very nice UI btw. I <3 it! ;-)
