### ISSUE TITLE
调用FreeUI的字体设置

### ISSUE THREAD

**Issue by ErVII7** [fafaraway/andromeda#128]
麦大，之前的版本我都可以在WA或者其他插件里选择FreeUI heavy之类的字体，我在core\media.lua里设置好了zhCN的路径，也在Fonts里面放好了字体文件，更新9.8.2后正常界面的字体没问题和以前一样，就是在其他插件里看不到字体选择了，都成了默认的楷体。
还有观察其他角色的时候看不到他们装等是正常的吗？还是我这里有什么错误设置。

**Comment by fafaraway** [comment]
自己的角色面板能看到装等么？

**Comment by ErVII7** [comment]
自己的角色可以看到装等，显示在右边属性栏的上面，但是观察其他人的话直接是没有右边这一块的，只有左边装备那一块

**Comment by fafaraway** [comment]
没有这个功能，我还以为你说的装备格子上的装等。

**Comment by ErVII7** [comment]
好的，是正常的就明白了，谢麦大解决
