### ISSUE TITLE
Some auras not working

### ISSUE THREAD

**Issue by allexffs** [fafaraway/andromeda#131]
Some of the auras are not working when using BlacknWhite. on my warlock, immolate and fear is not working so far. I have added them by spell name on the white list with all the others

**Comment by fafaraway** [comment]
“Spell Name” is not supported, you have to fill in "Spell ID".

**Comment by allexffs** [comment]
Oh I meant spell ID, they are added to the whitelist just fine, does not appear on the nameplates tho

**Comment by fafaraway** [comment]
Did some tests to confirm that the blacklist and whitelist filters are working.
Are you filling in the SpellID of the SPELL? it needs to be the SpellID of the AURA.

For example, SpellID of immolate spell is '348', and SpellID of immolate debuff is '157736', you have to fill in '157736' to track immolate debuff.

**Comment by allexffs** [comment]
I might be really stupid here, I didnt even think of that they had different spell IDs, i will check it out

**Comment by allexffs** [comment]
It does seem like you are correct, I did put in the spell ID, not the debuff Spell ID
