### ISSUE TITLE
友方姓名版名字模式(大秘境中)

### ISSUE THREAD

**Issue by Humwq** [fafaraway/andromeda#134]
9.8.6后  CVars强制开启了友方玩家和仆从的姓名版  以便显示名字模式。我挺喜欢的
问题在于 副本里(大米，团本未测试),暴雪禁用了友方的姓名版  导致给TN的标记没有正确显示在名字中央，显示在了原血条位置的左侧。
这导致了标记不在人物附近 像躲顺劈这种场景 无法准确定位T的位置
![图片](https://user-images.githubusercontent.com/9313456/175104520-623764a0-d793-419b-a2ea-b63142b9182e.png)

目前解决办法是 手动关闭 游戏-名字 里的友方玩家选项  但是RL或者重新进入游戏 会再次开启 得再改一下
![图片](https://user-images.githubusercontent.com/9313456/175104633-5ff4a6b7-d06b-40e9-abe7-34ad07c57430.png)

问题不大 只是有点不习惯

是否可以在GUI的姓名版栏里增加一个选项  可以根据情况选择开/关 这样就完美了

![图片](https://user-images.githubusercontent.com/9313456/175103430-d42394b0-b521-48a8-bfa3-11cde42f872e.png)
目前这三项关闭 友方仍然显示血条 还是要去界面-游戏-名字那里去关一下
或者副本里也像副本外一样 标记显示在中间位置
![图片](https://user-images.githubusercontent.com/9313456/175104049-55b4251b-9bff-4c36-81a2-e128216e63a1.png)

**Comment by Humwq** [comment]
默认开启 副本外  完美
![图片](https://user-images.githubusercontent.com/9313456/175105509-07754116-8d42-4891-8813-36263d94f993.png)

默认 副本内  玩家自身的标记没问题 队友/仆从的标记跑到右边挺远去了
![图片](https://user-images.githubusercontent.com/9313456/175105796-14c7a92b-36a8-4009-b9a7-cffe5e6da336.png)

副本内 关闭友方姓名版 
![图片](https://user-images.githubusercontent.com/9313456/175105975-56b01976-1a55-4d5f-b824-cf9da3dda902.png)
![图片](https://user-images.githubusercontent.com/9313456/175106010-9a5bcaa3-77be-4eca-ad01-65e623eba9ee.png)

**Comment by fafaraway** [comment]
副本内友方姓名板是受保护的，不能修改，只不过用暴雪自己的cvar隐藏了血条，但是团队标记仍然是锚在血条上，所以是偏的。
解决方法，禁用友方姓名板名字模式，或者在副本里关闭友方血条。

**Comment by Humwq** [comment]
禁用友方姓名板名字模式 会显示血条  每次RL都会出现  
有没有命令一直关闭友方血条呢

**Comment by Humwq** [comment]
/modules/nameplate/nameplate.lua 55行  强制打开了友方姓名版 
即便在GUI里取消勾选名字模式，这个CVar还是会自动打开友方血条
