### ISSUE TITLE
Bonjour 麦大!!! Long time no see^^ 

### ISSUE THREAD

**Issue by Oo-Lucas-oO** [fafaraway/andromeda#135]
好久不见喽~~~😆

怀旧服免费坐骑+1赶紧冲了张卡上去看看。。。来下载插件发现换名了😄

emmm...鼓捣了半天心满意足的开始在魔兽世界蹦迪。但是猛然发现不能一直比较装备了要按shift才可以。于是我就大退跑到config里面加了一个SET alwaysCompareItem "1" 这个，保存又重新登录游戏发现  esc→点击插件  会出现这种情况

![1663137802888](https://user-images.githubusercontent.com/14848127/190079800-d062c681-fc6a-4d01-8a9b-5cc9ef6b864e.png)

报错信息是
Message: Interface\SharedXML\AddonList.lua:265: attempt to index local 'checkedTexture' (a nil value)
Time: Wed Sep 14 14:44:22 2022
Count: 3
Stack: Interface\SharedXML\AddonList.lua:265: attempt to index local 'checkedTexture' (a nil value)
[string "@Interface\SharedXML\AddonList.lua"]:265: in function <Interface\SharedXML\AddonList.lua:253>
[string "@Interface\SharedXML\AddonList.lua"]:304: in function <Interface\SharedXML\AddonList.lua:276>
[string "=[C]"]: in function `AddonList_Update'
[string "@Interface\SharedXML\AddonList.lua"]:458: in function `AddonListScrollFrame_OnVerticalScroll'
[string "*:OnVerticalScroll"]:1: in function <[string "*:OnVerticalScroll"]:1>
[string "=[C]"]: in function `SetVerticalScroll'
[string "@Interface\SharedXML\SecureUIPanelTemplates.lua"]:64: in function <Interface\SharedXML\SecureUIPanelTemplates.lua:63>
[string "=[C]"]: in function `SetValue'
[string "@Interface\SharedXML\SharedUIPanelTemplates.lua"]:191: in function <Interface\SharedXML\SharedUIPanelTemplates.lua:185>

Locals: checked = 2
checkButton = AddonListEntry2Enabled {
 state = 0
 shadow = <unnamed> {
 }
 __gradient = <unnamed> {
 }
 __bg = <unnamed> {
 }
 PixelSnapDisabled = true
 bg = <unnamed> {
 }
 0 = <userdata>
}
checkedTexture = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = true
(*temporary) = <userdata>
(*temporary) = BasicMessageDialog {
 0 = <userdata>
 Text = <unnamed> {
 }
 Border = <unnamed> {
 }
}
(*temporary) = "attempt to index local 'checkedTexture' (a nil value)"

使用环境删除了3大件，只加载了仙女座。

不太清楚是不是跟仙女座有关系还是暴雪粑粑不让这么改了还是我放在interface里地材质出了问题。。。所以上来问一下🙃

哦还有就是，现在怎么改字体路径啊麦大，我去discord有一个也是关于字体你回复的是仙女座调用默认字体，但是在游戏里面不是我放在font里的ARKai_C.ttf的字体，我在core里也没找到字体路径（我承认我没有特别仔细地搜索。。。）。

最后是迟到的中秋问候~~🖖

**Comment by fafaraway** [comment]
这个报错和你添加cvar没有关系，下次更新会彻底解决这个报错。
修改字体指向在`core/media.lua`里和以前一样。

**Comment by Oo-Lucas-oO** [comment]
好的麦大～～
真高兴你还在更新这个插件。10.0再见咯～
🖖
