### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by zenjaa-git** [fafaraway/andromeda#137]
Hello !
The 10.0 Update does not load properly for me. I am stuck in the loading screen. 
Since I cant login, I cannot provide any type of lua errors - sorry for that. If I disable the math.lua file the game lets me login. But then of course the UI does not load properly. 
Maybe you know, whats happening. 

Thank you! Cheers!

**Comment by fafaraway** [comment]
Are you using the latest `10.0.0-alpha-2`?

**Comment by Suggles-sudo** [comment]
I too am experiencing the same issue. Did a removal of settings and then deleted the add on. Installed using alpha-2 version. Loading screen completes bar, I hear the sound in game, but the loading screen persists. Also, I have disabled all other addons to rule those out so only Andromeda is active to load.

**Comment by fafaraway** [comment]
> I too am experiencing the same issue. Did a removal of settings and then deleted the add on. Installed using alpha-2 version. Loading screen completes bar, I hear the sound in game, but the loading screen persists. Also, I have disabled all other addons to rule those out so only Andromeda is active to load.

What is the language of your game client?

**Comment by Suggles-sudo** [comment]
> > I too am experiencing the same issue. Did a removal of settings and then deleted the add on. Installed using alpha-2 version. Loading screen completes bar, I hear the sound in game, but the loading screen persists. Also, I have disabled all other addons to rule those out so only Andromeda is active to load.
> 
> What is the language of your game client?

English

**Comment by Suggles-sudo** [comment]
> > > I too am experiencing the same issue. Did a removal of settings and then deleted the add on. Installed using alpha-2 version. Loading screen completes bar, I hear the sound in game, but the loading screen persists. Also, I have disabled all other addons to rule those out so only Andromeda is active to load.
> > 
> > 
> > What is the language of your game client?
> 
> English

Happy to do a screen share in discord or what not if it helps?

**Comment by fafaraway** [comment]
> > > > I too am experiencing the same issue. Did a removal of settings and then deleted the add on. Installed using alpha-2 version. Loading screen completes bar, I hear the sound in game, but the loading screen persists. Also, I have disabled all other addons to rule those out so only Andromeda is active to load.
> > > 
> > > 
> > > What is the language of your game client?
> > 
> > 
> > English
> 
> Happy to do a screen share in discord or what not if it helps?

Have you encountered similar situations with andromeda before, I mean when the game version 9.2.5 or 9.2.7?

**Comment by Suggles-sudo** [comment]
> > > > > I too am experiencing the same issue. Did a removal of settings and then deleted the add on. Installed using alpha-2 version. Loading screen completes bar, I hear the sound in game, but the loading screen persists. Also, I have disabled all other addons to rule those out so only Andromeda is active to load.
> > > > 
> > > > 
> > > > What is the language of your game client?
> > > 
> > > 
> > > English
> > 
> > 
> > Happy to do a screen share in discord or what not if it helps?
> 
> Have you encountered similar situations with andromeda before, I mean when the game version 9.2.5 or 9.2.7?

No, the UI has been flawless before - and that's with having additional addons installed.

**Comment by Suggles-sudo** [comment]
> 

Update on steps followed so far - Renamed original AddOns folder, deleted contents of WTF and SavedVariables folders and reinstalled Andromeda alpha 2. Same results.

**Comment by zenjaa-git** [comment]
Exact same for me as Suggles-sudo described. Never before experienced problems. Deleted all WTF and addon data and did a clean re-install after but the problem persists. 
I am using the english client aswell.

**Comment by Urguk** [comment]
I'm have a fresh system OS install and Blizzard Battle.Net US English client installed. No other addons have been loaded on this system before or  the game before the pre-patch. I see the name menu and the loading screen. Goes to complete and I can hear the sound and music playing but unable to see or interact with the game at all.

**Comment by Urguk** [comment]
I just pulled the latest development. I was able to get pass the loading screen into the game. However the install widget is not showing any text and there are a few error around fonts.

![WoWScrnShot_103022_092526](https://user-images.githubusercontent.com/369974/198881032-15cc779c-eff0-4b4e-a7c3-053819aae5ae.jpg)

![WoWScrnShot_103022_092552](https://user-images.githubusercontent.com/369974/198881040-d488f0f6-8235-4666-ad25-04316d1fc102.jpg)

**Comment by zenjaa-git** [comment]
I implemented the changes that fafaraway did yesterday manually. One of those changes solved the problem for me and I am now able to get into the game and the addon loads properly.

**Comment by Urguk** [comment]
After I hit cancel and do /and gui this is what I see.

![WoWScrnShot_103022_092835](https://user-images.githubusercontent.com/369974/198881144-0c8cfd18-3f98-41ab-b92a-baf0bdf38f84.jpg)

**Comment by Urguk** [comment]
Think the below maybe one of the issue with fonts.

andromeda\modules\map line 262
        text:SetText('') If I change it to text:SetText() and reload the error goes away.

**Comment by Urguk** [comment]
> 

were able to see the install and configuration options?

**Comment by fafaraway** [comment]
try `alpha-3` and see if it solves the problem

**Comment by Urguk** [comment]
Loading screen is fix but still having the same issue with the install and SetText:( ) error and no text is showing  in the GUI.

**Comment by fafaraway** [comment]
According to your screenshot you are using the unpackaged development version, that's why the text is not displayed.
https://github.com/fafaraway/andromeda/releases/download/10.0.0-alpha-3/andromeda-10.0.0-alpha-3.zip

**Comment by Urguk** [comment]
I do not see anything else but development. I pull this into Git desktop and load it into my addons folder. I see the alpha 3 in the history so it should be there. However I will use your zip file and test.

**Comment by Urguk** [comment]
ok that worked thanks

**Comment by Suggles-sudo** [comment]
Alpha 3 seems to have loaded and configured! Will continue testing.
________________________________
