### ISSUE TITLE
史诗钥匙界面

### ISSUE THREAD

**Issue by harukayami** [fafaraway/andromeda#14]
hi，我来发这里啦~！根据楼上的同志的回复，意思应该是打了2层就会导致这个报错，我现在史诗钥匙界面啥都看不到，今天CD更新了也一样，想要脱离这样一头雾水的苦海（捂脸）

**Comment by fafaraway** [comment]
那你去打个高层的啊，我没打过2层的根本没法判断是什么问题啊，话说为啥还有人打2层的。。

**Comment by harukayami** [comment]
> 那你去打个高层的啊，我没打过2层的根本没法判断是什么问题啊，话说为啥还有人打2层的。。

说来我也后悔，是带公会回归的老人……他的钥匙，高层我十几层都打了，但是只要那个2层的还在，史诗钥匙界面就还是这个样子
![51911951-0f849500-240e-11e9-87b7-77156e372c11](https://user-images.githubusercontent.com/20994123/52048209-c8211480-2585-11e9-9938-e84867fe0c4b.png)
（图还是当天的，没重新截，大同小异）

**Comment by fafaraway** [comment]
在控制台里禁用全局皮肤以后这个史诗钥石的界面正常么？
有没有输出报错信息？
其他没打过2层的号有这个问题么？

**Comment by harukayami** [comment]
禁用全局皮肤后还是这样，我就玩一个号……报错信息那天反馈过，如下：
159x ...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:404: attempt to index local 'color' (a nil value)
...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:404: in function `SetUp'
...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:208: in function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:155>
[C]: ?
[C]: in function `ChallengesFrame_Update'
...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:126: in function <...dOns\Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:121>

Locals:
self = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:412
 HighestLevel = <unnamed> {
 }
 mapID = 252
 Icon = <unnamed> {
 }
 SetUp = <function> defined @Blizzard_ChallengesUI\Blizzard_ChallengesUI.lua:388
}
mapInfo = <table> {
 id = 252
 level = 2
 inTime = true
 quality = -1
}
isFirst = false
_ = "风暴神殿"
_ = 252
_ = 2340
texture = 2178732
color = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "2"
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"

**Comment by harukayami** [comment]
专门去找了个高层风暴的钥匙打掉后……就解决了
