### ISSUE TITLE
Russians Fonts

### ISSUE THREAD

**Issue by unw1s3** [fafaraway/andromeda#15]
Hello. Can you add support of Cyrillic fonts?! Because somewhere there is "?????????" instead of words.
![wowscrnshot_020319_232803](https://user-images.githubusercontent.com/44213411/52182245-527aaa00-280c-11e9-9dfd-c43b5b456105.jpg)
![wowscrnshot_020319_232808](https://user-images.githubusercontent.com/44213411/52182246-527aaa00-280c-11e9-9692-c2fbb0eaa826.jpg)
![wowscrnshot_020319_233140](https://user-images.githubusercontent.com/44213411/52182247-527aaa00-280c-11e9-8925-9a393652e0d3.jpg)

**Comment by fafaraway** [comment]
added a new font for russian client, try new updates.

**Comment by unw1s3** [comment]
that works, thank you!
