### ISSUE TITLE
Cant see items on Weekly Loot chest 

### ISSUE THREAD

**Issue by Evonos** [fafaraway/andromeda#153]
Title pretty much

**Comment by fafaraway** [comment]
Click on those black blocks to show the rewards, this is to simulate the feeling of lotto.

**Comment by Evonos** [comment]
Can we get a toggle to disable this maybe? looks more like a bug :/

**Comment by fafaraway** [comment]
I will add a option to disable it in the future.

**Comment by Evonos** [comment]
thanks ! :)
