### ISSUE TITLE
how can i use the NOTIFICATION.Frame.clickFunc ?

### ISSUE THREAD

**Issue by Smallinger** [fafaraway/andromeda#155]
Hey i want to add a function on the rare.lua in notification, so that i create a map pin marker if i click on the notification.

how i can use the NOTIFICATION.Frame.clickFunc ?

**Comment by Smallinger** [comment]
i fount out if i add this

`
local mapPoint = UiMapPoint.CreateFromVector2D(mapID, position)
C_Map.SetUserWaypoint(mapPoint)
`
            
to following file modules/notification/rare.lua 44-45

then i get every time a waypoint after a notification was made, how can i add a left click ?

**Comment by fafaraway** [comment]
modules/notification/rare.lua 34
replace `nil` with the func you add

like this
```
local function myClickFunc()
        -- do something
end

F:CreateNotification(
            _G.GARRISON_MISSION_RARE,
            tex .. (info.name or ''),
            myClickFunc,
            'Interface\\ICONS\\INV_Misc_Map_01'
        )
```

**Comment by Smallinger** [comment]
hey thx i made a pull request would love to see the changes in the next release.
https://github.com/fafaraway/andromeda/pull/159
