### ISSUE TITLE
Hi 麦大～～～小地图出现了一个报错。

### ISSUE THREAD

**Issue by Oo-Lucas-oO** [fafaraway/andromeda#158]
Bonjour 麦大～～～我又又又来了😄

目前国服无论如何1月23号都要关了，把以前上学时候的欧服账号捡起来了，先玩儿一阵子。。。

然后我改了下语言登陆发用法语客户端登陆英区服务器，进入游戏后发现小地图下面游戏原生的小菜单和背包栏没有隐藏。像这样：

![image](https://user-images.githubusercontent.com/14848127/212524936-fa3240bf-ab05-4e31-a0db-1bf61f47dc4d.jpeg)

右下角小地图下面那个位置，插件的版本号是10.013

只加载了仙女座，国服的三大件数据都删了。也是没有看到报错信息，我又删除三大件，改成了英语进入游戏也是一样的情况。

后来不确定是不是语言的原因，我又登陆PTR试了试，PTR游戏语言一只是英文没改动过。然后上去以后也是一样的问题，但是多了一个报错信息：

Message: Interface/AddOns/andromeda/modules/map/minimap.lua:148: attempt to index local 'mail' (a nil value)
Time: Sun Jan 15 13:31:14 2023
Count: 1
Stack: Interface/AddOns/andromeda/modules/map/minimap.lua:148: attempt to index local 'mail' (a nil value)
[string "@Interface/AddOns/andromeda/modules/map/minimap.lua"]:148: in function `CreateMailButton'
[string "@Interface/AddOns/andromeda/modules/map/minimap.lua"]:617: in function `SetupMinimap'
[string "@Interface/AddOns/andromeda/modules/map/worldmap.lua"]:156: in function `OnLogin'
[string "@Interface/AddOns/andromeda/core/init.lua"]:172: in function `func'
[string "@Interface/AddOns/andromeda/core/init.lua"]:93: in function <Interface/AddOns/andromeda/core/init.lua:88>

Locals: self = <table> {
 MenuList = <table> {
 }
 WorldMapScale = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:119
 SetupWorldMap = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:131
 CreateDifficultyFlag = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:273
 AddOnIconCollector = <function> defined @Interface/AddOns/andromeda/modules/map/collector.lua:196
 CreateMailButton = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:144
 MapData_RefreshOverlays = <function> defined @Interface/AddOns/andromeda/modules/map/reveal.lua:23
 WhoPings = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:412
 GetPlayerMapPos = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:8
 UpdateMapID = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:77
 GetCursorCoords = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:34
 UpdateMinimapScale = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:117
 UpdateMapScale = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:106
 WorldMapReveal = <function> defined @Interface/AddOns/andromeda/modules/map/reveal.lua:137
 UpdateRenownLevel = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:31
 Bar_Update = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:87
 OnLogin = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:150
 GetMinimapShape = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:132
 SetupMinimap = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:606
 RestyleHybridMinimap = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:100
 CreatePendingInvitation = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:157
 CreateZoneText = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:464
 UpdateWorldMapReveal = <function> defined @Interface/AddOns/andromeda/modules/map/reveal.lua:144
 ParagonReputationSetup = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:309
 MapData_ResetTexturePool = <function> defined @Interface/AddOns/andromeda/modules/map/reveal.lua:131
 ExpansionMenuList = <table> {
 }
 RawMapData = <table> {
 }
 CreateProgressBar = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:294
 SetupScript = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:280
 BuildDropDown = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:562
 SoundVolume = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:507
 Bar_OnEnter = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:153
 CreateBar = <function> defined @Interface/AddOns/andromeda/modules/map/progressbar.lua:63
 CreateQueueStatusButton = <function> defined @Interface/AddOns/andromeda/modules/map/minimap.lua:370
 AddCoords = <function> defined @Interface/AddOns/andromeda/modules/map/worldmap.lua:85
 UpdateMinimapFader = <function> defined @Interface/AddOns/andromeda/modules/map/fader.lua:14
 InitRenownLevel = <fu

报错信息就到这里了，再往下没有了。。。

然而有些奇怪的是，我看discord那些老外好像没人反馈这个问题？。。。是不是他们没更新到最新版本所以没发现。。。囧。。。

哈哈哈

麦大辛苦～～～🖖

**Comment by Oo-Lucas-oO** [comment]
额，补充下。

正式服：登陆流亡岛以后小地图就正常了。囧。。。

PTR那个我把小号建在血精灵新手村了，不知道为啥也有这个错误。

正式服上岛以后就正常了。🖖

**Comment by fafaraway** [comment]
这是10.0.5的改动，暴雪改了小地图邮件图标的命名，下次更新会兼容10.0.5

**Comment by Oo-Lucas-oO** [comment]
好哒麦大～～～😄 🖖
