### ISSUE TITLE
WOW 10.05更新后出现的bug

### ISSUE THREAD

**Issue by Oo-Lucas-oO** [fafaraway/andromeda#161]
哈喽麦大～～～
今天欧服更新完上去以后出现了bug，变成这样了，我用的是curse上下载的10.014beta版本，前几天看curseforge上有更新我就直接更了😀：

![image](https://user-images.githubusercontent.com/14848127/214539779-f61083a4-bfd3-41a4-9377-e4bbb2e9756d.jpeg)

报错信息有：

Message: ...s/andromeda/modules/theme/blizzard/FrameXML/Bags.lua:154: attempt to index field 'BankPortraitTexture' (a nil value)
Time: Wed Jan 25 18:23:33 2023
Count: 1
Stack: ...s/andromeda/modules/theme/blizzard/FrameXML/Bags.lua:154: attempt to index field 'BankPortraitTexture' (a nil value)
[string "@Interface/AddOns/andromeda/modules/theme/blizzard/FrameXML/Bags.lua"]:154: in function `func'
[string "@Interface/AddOns/andromeda/modules/theme/theme.lua"]:28: in function `LoadAddOnSkins'
[string "@Interface/AddOns/andromeda/modules/theme/theme.lua"]:105: in function `OnLogin'
[string "@Interface/AddOns/andromeda/core/init.lua"]:172: in function `func'
[string "@Interface/AddOns/andromeda/core/init.lua"]:93: in function <Interface/AddOns/andromeda/core/init.lua:88>

Locals: (*temporary) = nil
(*temporary) = nil
(*temporary) = "BORDER"
(*temporary) = <userdata>
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = 0
(*temporary) = <userdata>
(*temporary) = false
(*temporary) = nil
(*temporary) = Texture {
 0 = <userdata>
 PixelSnapDisabled = true
}
(*temporary) = false
(*temporary) = 0.250000
(*temporary) = <table> {
 b = 0.100000
 g = 0.100000
 r = 0.100000
}
(*temporary) = 0.550000
(*temporary) = "attempt to index field 'BankPortraitTexture' (a nil value)"
C = <table> {
 SCREEN_HEIGHT = 1080
 Assets = <table> {
 }
 b = 0.447059
 TrashUnitsList = <table> {
 }
 Frames = <table> {
 }
 CharacterSettings = <table> {
 }
 PartyPetFlags = 4370
 IsInMyGroup = <function> defined @Interface/AddOns/andromeda/core/constants.lua:123
 NameplateAuraWhiteList = <table> {
 }
 r = 0.666667
 IS_DEVELOPER = false
 RaidPetFlags = 4372
 ClassColors = <table> {
 }
 CornerSpellsList = <table> {
 }
 QualityColors = <table> {
 }
 ADDON_TITLE = "AndromedaUI"
 IS_NEW_PATCH = true
 IgnoreQuestNPC = <table> {
 }
 AnnounceableSpellsList = <table> {
 }
 COLORFUL_ADDON_TITLE = "AndromedaUI"
 ASSET_PATH = "Interface\AddOns\andromeda\assets\"
 MajorSpellsList = <table> {
 }
 ClassList = <table> {
 }
 YELLOW_COLOR = ""
 MY_NAME = "Lindit"
 MOUSE_RIGHT_BUTTON = "  "
 BadBoys = <table> {
 }
 MULT = 1.001565
 WHITE_COLOR = ""
 Themes = <table> {
 }
 BloodlustDebuffsList = <table> {
 }
 MY_CLASS = "HUNTER"
 MOUSE_LEFT_BUTTON = "  "
 MOUSE_MIDDLE_BUTTON = "  "
 AddonThemes = <table> {
 }
 DevsList = <table> {
 }
 MY_FULL_NAME = "Lindit-Krasus"
 GREEN_COLOR = ""
 BlizzThemes = <table> {
 }
 RaidDebuffsBlackList = <table> {
 }
 IsMyPet = <function> defined @Interface/AddOns/andromeda/core/constants.lua:116
 SpecialUnitsList = <table> {
 }
 NameplateAuraBlackList = <table> {
 }
 ADDON_VERSION = "10.1.4-beta"
 GREY_COLOR = ""
 INFO_COLOR = ""
 MY_REALM = "Krasus"
 DB = <table> {
 }
 LINE_STRING = "---------------"
 MyRole = "Melee"
 RED_COLOR = ""
 MY_CLASS_COLOR = ""
 MY_FACTION = "Alliance"
 TEX_COORD = <table> {
 }
 g = 0.827451
 BLUE_COLOR = ""
 UI_GAP = 33
 ADDON_NAME = "andromeda"
 AccountSettings = <table> {
 }
 TalentCDFixList = <table> {
 }
 PartySpellsList = <table> {
 }
 RaidBuffsWhiteList = <table> {
 }
 PowerUnitsList = <table> {
 }
 NameplateShowTargetNPCsList = <table> {
 }
 SCREEN_WIDTH = 1920
}
F = <table> {
 GetScreenQuadrant = <function> defined @Interface/AddOns/andromeda/core/math.lua:168
 CreateGlowFrame = <function> defined @Interface/AddOns/andromeda/core/functions.lua:603
 ReskinDropDown = <function> defined @Interface/AddOns/andromeda/core/functions.lua:1710
 LockCVar = <function> defined @Interface/AddOns/andromeda/core/functions.lua:169
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/andromeda/libraries/AceTimer-3.0/AceTimer-3.0.lua:147
 SecureHook = <function> defined @Interface/AddOns/andromeda/libraries/AceHook-3.0/AceHook-3.0.lua:335
 UIFrameFade_OnUpdate = <function> defined @Interface/AddOns/andromeda/core/animation.lua:239
 SpeedAnimationGroup = <function> defined @Int

其他插件都没加载，只有仙女座，删除了三大件。辛苦了麦大哈哈～～

**Comment by Oo-Lucas-oO** [comment]
补充个发现的问题：人物界面一键脱装备的功能无了，还有插件美化皮肤大部分失效了。像这样：

![image](https://user-images.githubusercontent.com/14848127/214563345-66543132-264b-4e45-8011-ea62ffc6c483.jpeg)

我又发现打开仙女座的背包模块大部分功能就好了，因为我想集中收集下问题然后一汽起贴出来，把carg关掉以后打开andromeda的背包模块发现大部分功能又正常了。但是还有些小问题，右下角原生小菜单还是一直显示，但是这些问题都没有收到报错。

**Comment by fafaraway** [comment]
试试 `10.1.5`

**Comment by Oo-Lucas-oO** [comment]
麦大赛高！！！😍感谢修复哈哈～～～😄

关掉背包模块没报错了，正常使用。小地图下面的小菜单好像还是没有正确隐藏，不过现在不影响使用了。其实最一开始发现的时候我还以为是新功能。。哈哈哈😊～

辛苦啦～～～🖖
