### ISSUE TITLE
TargetTarget, Focus & FocusTarget Castbar

### ISSUE THREAD

**Issue by Flowieyay** [fafaraway/andromeda#2]
Hey there,

I just stumbled across an Issue(?), where I could not move the Castbars of, either the TargetTarget nor the FocusTarget on the most recent version. aswell as the FocusCastbar. aswell as the Icons of these castbars which can not be moved either and therefor block some vision as seen in the uploaded file.
As I'm not much into Scripting i had a buddy of mine look over it and he could not find a fix to it aswell.

![free](https://user-images.githubusercontent.com/42893645/44950009-9886a880-ae3d-11e8-9958-b5510fd2dd69.JPG)

**Comment by fafaraway** [comment]
a simple fix for your layout
open this file `FreeUI/scripts/unitframes/unitframes.lua`
find `cb.OnUpdate = cast.OnCastbarUpdate`
then add following code before that line

`if self.unitStyle == "focus" then`
		`cb:ClearAllPoints()`
		`cb:SetPoint("BOTTOMRIGHT", self, "TOPRIGHT", 0, 30)`
		`iconFrame:ClearAllPoints()`
		`iconFrame:SetPoint("LEFT", cb, "RIGHT", 4, 0)`
	`elseif self.unitStyle == "targettarget" then`
		`iconFrame:ClearAllPoints()`
		`iconFrame:SetPoint("LEFT", self, "RIGHT", 4, 0)`
	`elseif self.unitStyle == "focustarget" then`
		`iconFrame:ClearAllPoints()`
		`iconFrame:SetPoint("RIGHT", self, "LEFT", -4, 0)`
	`end`

**Comment by Flowieyay** [comment]
Thank you very much.
