### ISSUE TITLE
options menu no text 

### ISSUE THREAD

**Issue by Proxyworm** [fafaraway/andromeda#29]
![WoWScrnShot_093019_203550](https://user-images.githubusercontent.com/8519355/65932287-ee6fac00-e3c1-11e9-92c4-fae6542b1cc9.jpg)

**Comment by fafaraway** [comment]
use new version.

**Comment by Proxyworm** [comment]
I literally am, my svn is (https://github.com/Solor/FreeUI.git) I already cleared and checked out again same issue 

Note the version number in the screenshot

**Comment by fafaraway** [comment]
sorry, my mistake, haven't played live server for a while 😆

**Comment by Proxyworm** [comment]
as of the latest commit (96b5625) confirming that I again have options text
