### ISSUE TITLE
Cant craft without a crash

### ISSUE THREAD

**Issue by jakeface1** [fafaraway/andromeda#32]
Im not sure if this is related to FreeUI and an interaction with another addon. When I craft WoW crashes randomly., when I disable freeUI I can mass craft without any issues. This is the error message I get. 
![craftcrash (2)](https://user-images.githubusercontent.com/43097188/66324346-daa8d600-e8ea-11e9-958a-06ad35fe9dba.png)

**Comment by firstmidnight** [comment]
I have same problem with a clean install of free ui even if anything else is disabled.

**Comment by Smallinger** [comment]
same here found out, after disabling `<Include file='scripts\chat\chat.xml'/>` in the FreeUI.XML the crash is gone.

**Comment by Smallinger** [comment]
More information, after disable the function `function module:Abbreviate()` in FreeUI/scripts/chat/abbreviate.lua, the crashing is gone... i check now why is crashing....

**Comment by Smallinger** [comment]
ok, last comment, the problem is on line 161, 162, in the file `\FreeUI\scripts\chat\abbreviate.lua` after removing these lines no crashing.

**Comment by firstmidnight** [comment]
It works, thank you so much!
