### ISSUE TITLE
Some of the text is still very much chinese

### ISSUE THREAD

**Issue by allexffs** [fafaraway/andromeda#43]
Some of the text is still very much chinese, tried all the releases, 50 % of the text on the infobar is chinese still, and also alot of the 
notifications are still chinese, looked in the locales/ enUS.lua, and it looks like most of it should be translated ? 
![WoWScrnShot_090520_185609](https://user-images.githubusercontent.com/19673212/92309936-d88f4180-efa9-11ea-8aec-12d6a550f10f.jpg)
![WoWScrnShot_090520_185620](https://user-images.githubusercontent.com/19673212/92309943-e2b14000-efa9-11ea-9364-f7e890e1f2fb.jpg)
![WoWScrnShot_090520_185631](https://user-images.githubusercontent.com/19673212/92309945-e47b0380-efa9-11ea-8e53-90050cc8f19e.jpg)
![WoWScrnShot_090520_185642](https://user-images.githubusercontent.com/19673212/92309947-e5ac3080-efa9-11ea-97fc-f2008cdc79eb.jpg)

**Comment by allexffs** [comment]
New updates seems to have fixed most of it

**Comment by fafaraway** [comment]
any more unfinished text string on english client?
