### ISSUE TITLE
Pixel style buttons

### ISSUE THREAD

**Issue by zkq426** [fafaraway/andromeda#46]
自制了几个像素风格素材，包括背包、银行按钮和close、arrow。
2k分辨率下效果如图（4k下没测，素材大小128*128应该没问题），想问下能不能合。
![bag](https://user-images.githubusercontent.com/33888649/92490507-b30d6c80-f223-11ea-903f-04ed29e8e3de.PNG)
![bank](https://user-images.githubusercontent.com/33888649/92490543-bd2f6b00-f223-11ea-88ec-7db07052aa79.PNG)
![guild](https://user-images.githubusercontent.com/33888649/92495658-c3c0e100-f229-11ea-9081-3a03b4b18085.PNG)

另外close和arrow应该是缩放关系没法达到pixel perfect，固定16*16的大小乘上C.Mult也不行，请问有没有什么方法可以解决。

**Comment by fafaraway** [comment]
挺漂亮的，比我弄的精致多了，你发PR吧，我看看4k分辨率有没有问题 👍
正常来说如果在FreeUI的控制面板里把缩放设为1或者2就不会出现1px线条失真的问题，1是给1080p用的，2是给2160p用的，都能保证点对点完美，2k比较尴尬，我也不清楚大于1的情况下设为多少才能保证不失真。

**Comment by zkq426** [comment]
哦哦好的，我试试看2k要设多少。
还有一个问题，还有可能添加使用像素字体的选项吗，真的很喜欢以前的像素字体。

**Comment by fafaraway** [comment]
背包的图标挺好，但是 close 和 arrow 实在太细了

![WoWScrnShot_090920_075446](https://user-images.githubusercontent.com/156806/92531760-479ebb80-f272-11ea-87ba-b4b9128f047b.jpg)

**Comment by zkq426** [comment]
更新了下。
close改成了2px，arrow实心。
![guild1](https://user-images.githubusercontent.com/33888649/92590972-a8a8ac80-f2cf-11ea-92e0-a9271aae8108.PNG)

**Comment by fafaraway** [comment]
close 和 arrow 在 2160p 两倍缩放的情况下效果很差
这2个图标我觉得还是使用原来的，你如果喜欢可以放在自己的fork上
背包的图标没问题，可以先合并

**Comment by zkq426** [comment]
OK了解！
