### ISSUE TITLE
Cooldowns

### ISSUE THREAD

**Issue by allexffs** [fafaraway/andromeda#49]
Cooldowns gets stuck on the screen instead of flashing for a little while, before fading away very slowly sometimes, cant seem to recreate it, it happens randomly
![WoWScrnShot_091120_040549](https://user-images.githubusercontent.com/19673212/92950519-0f0f0580-f45d-11ea-9ccd-d1f78937f44e.jpg)

**Comment by fafaraway** [comment]
specific spell or totally random?

**Comment by allexffs** [comment]
Seems to be the same ones, they dont appear that frequently. differs from class to class ofcourse, i have disable CD pulse for now, but i could turn it back on and track what spells it is

EDIT: so far on the Demonhunter its: vengeful retreat and Immolation aura, Fel Rush


Mouse cursor trail also bugging out, not working at all sometimes and getting stuck in the "flash" animation
