### ISSUE TITLE
3 lua errors

### ISSUE THREAD

**Issue by allexffs** [fafaraway/andromeda#51]
4x ...eeUI\modules\theme\blizzard\Blizzard_Collections-1.0.lua:456: Usage: <unnamed>:SetFont("font", fontHeight [, flags])
[string "=[C]"]: in function `SetFont'
[string "@FreeUI\modules\theme\blizzard\Blizzard_Collections-1.0.lua"]:456: in function <...eeUI\modules\theme\blizzard\Blizzard_Collections.lua:451>
[string "=[C]"]: in function `LayoutCurrentPage'
[string "@Blizzard_Collections\Blizzard_HeirloomCollection.lua"]:515: in function `RefreshView'
[string "@Blizzard_Collections\Blizzard_HeirloomCollection.lua"]:47: in function <...Blizzard_Collections\Blizzard_HeirloomCollection.lua:19>
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:52: in function `CollectionsJournal_UpdateSelectedTab'
[string "@Blizzard_Collections\Blizzard_Collections-1.0.lua"]:6: in function `CollectionsJournal_SetTab'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = 16
(*temporary) = "OUTLINE"

-----------------------------------------------

50x FreeUI\modules\unitframe\elements.lua:1115: attempt to index local 'colors' (a nil value)
[string "@FreeUI\modules\unitframe\elements.lua"]:1115: in function <FreeUI\modules\unitframe\elements.lua:1100>
[string "@FreeUI\libs\oUF\elements\classpower.lua"]:197: in function <...rfaceFreeUI\libs\oUF\elements\classpower.lua:165>
[string "=(tail call)"]: ?
[string "@FreeUI\libs\oUF\ouf.lua"]:211: in function `func'
[string "@FreeUI\libs\oUF\events.lua"]:81: in function <FreeUI\libs\oUF\events.lua:79>
[string "=(tail call)"]: ?

Locals:
element = <table> {
 1 = <unnamed> {
 }
 2 = <unnamed> {
 }
 3 = <unnamed> {
 }
 4 = <unnamed> {
 }
 5 = <unnamed> {
 }
 6 = <unnamed> {
 }
 __owner = oUF_Player {
 }
 ClassPowerEnable = <function> defined @FreeUI\libs\oUF\elements\classpower.lua:225
 ForceUpdate = <function> defined @FreeUI\libs\oUF\elements\classpower.lua:220
 PostUpdate = <function> defined @FreeUI\modules\unitframe\elements.lua:1076
 ClassPowerDisable = <function> defined @FreeUI\libs\oUF\elements\classpower.lua:238
 UpdateColor = <function> defined @FreeUI\modules\unitframe\elements.lua:1100
 __max = 6
}
colors = nil
r = nil
g = nil
b = nil
(*temporary) = "ROGUE"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'colors' (a nil value)"
C = <table> {
 LineString = "|cff7f7f7f---------------"
 Assets = <table> {
 }
 CustomUnits = <table> {
 }
 MyName = "Stabmyhole"
 Frames = <table> {
 }
 CharacterSettings = <table> {
 }
 TexCoord = <table> {
 }
 Mult = 0.714286
 PartyPetFlags = 4370
 MyRealm = "Outland"
 Client = "enUS"
 GreenColor = "|cff20ff20"
 isChinses = false
 YellowColor = "|cffffff00"
 ScreenWidth = 3840
 MyColor = "|cffefdd7a"
 RaidPetFlags = 4372
 BlizzThemes = <table> {
 }
 MyRace = "ZandalariTroll"
 MyLevel = 120
 ClassColors = <table> {
 }
 MyFaction = "Horde"
 DevsList = <table> {
 }
 GreyColor = "|cff7f7f7f"
 Title = "|cffe6e6e6Free|r|cffefdd7aUI|r"
 IsMyPet = <function> defined @FreeUI\core\constants.lua:175
 RedColor = "|cffff2020"
 b = 0.480000
 g = 0.870000
 r = 0.940000
 ShowPowerList = <table> {
 }
 ScreenHeight = 1600
 Themes = <table> {
 }
 BadBoys = <table> {
 }
 Role = "Melee"
 InfoColor = "|cffe9c55d"
 ClassBuffs = <table> {
 }
 isCNPortal = false
 AccountSettings = <table> {
 }
 AuraBlackList = <table> {
 }
 AuraWhiteList = <table> {
 }
 TalentCDFix = <table> {
 }
 PartySpells = <table> {
 }
 QualityColors = <table> {
 }
 CornerBuffs = <table> {
 }
 PurpleColor = "|cffa571df"
 classmod = <table> {
 }
 AssetsPath = "FreeUI\assets\"
 MyClass = "ROGUE"
 RaidDebuffs = <table> {
 }
 OrangeColor = "|cffff7f3f"
 Version = "9.0.8"
 ClassList = <table> {
 }
 isNewPatch = false
 ReminderBuffs = <table> {
 }
 Support = "BfA"
 BlueColor = "|cff82c5ff"
}

-------------------------------------------------------------

62x ...ns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:366: attempt to index a nil value
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:366: in function `ApplyCurrentPosition'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:250: in function `SetNudgeVector'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:305: in function `CalculatePinNudging'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:343: in function `UpdatePinNudging'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:23: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:22>

Locals:
self = <unnamed> {
 Number = <unnamed> {
 }
 Highlight = <unnamed> {
 }
 PanTo = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:289
 zoomedInNudge = 0.250000
 UseFrameLevelType = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:394
 GetNudgeSourceZoomedInMagnitude = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:204
 SetScaleStyle = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:330
 GetNudgeSourcePinZoomedInNudgeFactor = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:240
 UpdateTooltip = <function> defined @Blizzard_SharedMapDataProviders\QuestDataProvider.lua:289
 GetMap = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:228
 ApplyFrameLevel = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:403
 ApplyCurrentPosition = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:365
 IsIgnoringGlobalPinScale = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:316
 style = "normal"
 endScale = 0.425000
 OnMouseEnter = <function> defined @Blizzard_SharedMapDataProviders\QuestDataProvider.lua:289
 OnMouseUp = <function> defined @Blizzard_SharedMapDataProviders\QuestDataProvider.lua:349
 OnAcquired = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:139
 PanAndZoomTo = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:294
 ApplyCurrentAlpha = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:386
 AssignQuestNumber = <function> defined @Blizzard_SharedMapDataProviders\QuestDataProvider.lua:336
 OnLoad = <function> defined @Blizzard_FlightMap\FM_QuestDataProvider.lua:24
 PushedTexture = <unnamed> {
 }
 OnReleased = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:143
 startAlpha = 1
 OnCanvasPanChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:304
 GetPosition = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:277
 SetNudgeFactor = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:257
 GetNudgeSourcePinZoomedOutNudgeFactor = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:236
 startScale = 0.412500
 OnClick = <function> defined @Blizzard_SharedMapDataProviders\QuestDataProvider.lua:332
 Texture = <unnamed> {
 }
 GetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:191
 OnMouseLeave = <function> defined @Blizzard_SharedMapDataProviders\QuestDataProvider.lua:327
 questID = 49930
 normalizedY = 0.620620
 GetNudgeTargetFactor = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:183
 GetFrameLevelType = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:399
 SetAlphaStyle = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:355
 SetScalingLimits = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:320
 normalizedX = 0.583043
 SetNudgeSourceRadius = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:187
 moveHighlightOnMouseDown = false
 GetGlobalPosition = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:282
 GetNudgeZoomFactor = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:262
 isSuperTracked = true
 OnCanvasScaleChanged = <function> defined @Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua:299
 zoomedOutNudge = 1
 SetAlphaLimits = <function> defin

**Comment by fafaraway** [comment]
try 9.1.0
