### ISSUE TITLE
No text in Config menu using latest version with no other addons

### ISSUE THREAD

**Issue by nissekaka** [fafaraway/andromeda#57]
I have tried reinstalling and have also tried using the precious release (which doesn't even load).
I have tried deleting WTF and Cache folders to no avail.

![image](https://user-images.githubusercontent.com/70889874/96336501-982ee300-1080-11eb-89e4-ec468c5f603e.png)

**Comment by fafaraway** [comment]
Yes, it's not finished yet, I really dont have much time to deal this for now 😂

**Comment by nissekaka** [comment]
> 
> 
> Yes, it's not finished yet, I really dont have much time to deal this for now 😂

Totally understandable! Is there anything I can do to help fixing this? Or is it a lot of work?

**Comment by jakeface1** [comment]
> > Yes, it's not finished yet, I really dont have much time to deal this for now 😂
> 
> Totally understandable! Is there anything I can do to help fixing this? Or is it a lot of work?

ATM I'm manually changing the settings in FreeUI.lua. Most of its there to mess with.

**Comment by nissekaka** [comment]
> 
> 
> > > Yes, it's not finished yet, I really dont have much time to deal this for now 😂
> > 
> > 
> > Totally understandable! Is there anything I can do to help fixing this? Or is it a lot of work?
> 
> ATM I'm manually changing the settings in FreeUI.lua. Most of its there to mess with.

Alright, found some settings I could tweak. Any idea how I can remove the cursor shine/glow effect?

**Comment by fafaraway** [comment]
> 
> Alright, found some settings I could tweak. Any idea how I can remove the cursor shine/glow effect?

@nissekaka you can use `/run FreeDB.appearance.cursor_trail = false` as a temporary solution, dont forget to `/rl` 👌

**Comment by fafaraway** [comment]
> 
> Totally understandable! Is there anything I can do to help fixing this? Or is it a lot of work?

it's okay, I'll keep working on it , thanks for supporting 😊

**Comment by nissekaka** [comment]
> 
> 
> > Alright, found some settings I could tweak. Any idea how I can remove the cursor shine/glow effect?
> 
> @nissekaka you can use `/run FreeDB.appearance.cursor_trail = false` as a temporary solution, dont forget to `/rl` 👌

Alright, thanks!

**Comment by fafaraway** [comment]
try 9.1.5
