### ISSUE TITLE
Pet standard UI issue.

### ISSUE THREAD

**Issue by jakeface1** [fafaraway/andromeda#6]
When I have a Warlock pet out and take a flight path, or enter a vehicle, the default unit frame for my pet shows. Could very well be another addon interfering. Its not happening 100% of the time and a /RL fixes it.

**Comment by fafaraway** [comment]
pretty sure it caused by other addon, you could only enable freeui to testing it 😆

**Comment by jakeface1** [comment]
Thanks for the reply! I figured that was the case. Cheers!
