### ISSUE TITLE
Issues with bags

### ISSUE THREAD

**Issue by allexffs** [fafaraway/andromeda#62]
![bags](https://user-images.githubusercontent.com/19673212/99917718-601b5f80-2d12-11eb-8aea-c04588419750.jpg),
pawn icons and boe icons stay stuck if something gets moved in the bags, stuck even after sorting think its all icons

**Comment by fafaraway** [comment]
what are those green arrow, another addon?

**Comment by allexffs** [comment]
Yeah its the addon called Pawn, it indicates if a gear piece is an upgrade from what you have equipped.
