### ISSUE TITLE
物品栏大数目显示超过格子了，建议缩写。

### ISSUE THREAD

**Issue by Humwq** [fafaraway/andromeda#73]
![图片](https://user-images.githubusercontent.com/9313456/102579868-5978e000-4138-11eb-9b3a-264e8f60a9ce.png)
例如图上的宠物护符1000一组  可以缩写为1K类似这样的处理。

**Comment by fafaraway** [comment]
好的，话说你这也缩的太小了，眼睛都要瞎了

**Comment by Humwq** [comment]
26 以前用cargBags Nivaya习惯了的大小   
1080P  太大了影响技能出手速度

**Comment by Humwq** [comment]
![图片](https://user-images.githubusercontent.com/9313456/102638779-0122fc00-4193-11eb-8417-9291ecacec33.png)
完美！
