### ISSUE TITLE
团队工具，遮挡了评级战场的资源显示框

### ISSUE THREAD

**Issue by Humwq** [fafaraway/andromeda#74]
就是就位确认 显示团队配置的 还有世界标记的那个工具栏  
挡住了评级战场里的资源显示模块
忘记截图

或者说是，在有资源的评级战场里，团队工具没有自适应调整位置,导致遮挡

**Comment by fafaraway** [comment]
团队工具可以移动的啊，你解锁后随便找个地方摆就是了

**Comment by Humwq** [comment]
这个知道，但是摆其他地方，好像也不太顺眼。。。。。。

**Comment by Humwq** [comment]
稍微往上调整了一下  下面基本能看到了  
感觉还行 暂时可以 就这样了
