### ISSUE TITLE
target unitframe name

### ISSUE THREAD

**Issue by rippolol** [fafaraway/andromeda#77]
I have problem with target name https://puu.sh/H31tP/f8f486c90f.png Its problem with fonts or what? How i could do full names on target frames ?

**Comment by fafaraway** [comment]
Is that russian?
Default font does not include cyrillic characters, you could simply replace it with other font.
`FreeUI\assets\fonts\condensed.ttf`

**Comment by rippolol** [comment]
Yes, it is russian. Only the first letters are not visible, the other part is visible

**Comment by rippolol** [comment]
So i replace font and it did not help. I think it is because the standard abbreviation method is not suitable for the Russian version of the game, i have the same problems with plater or suf if i wanna use short names

**Comment by fafaraway** [comment]
Ok, I'll disable this function on russian client in next release.

**Comment by rippolol** [comment]
Nice! Thank you !
