### ISSUE TITLE
快捷焦点问题＆pvp的tab

### ISSUE THREAD

**Issue by Humwq** [fafaraway/andromeda#80]
1，shift+左键点击的快捷焦点功能对框体失效。目前只能点模型，目标框体、小队框体、团队框体都不行
评级战场有BGE还好，jjc的时候不能快速点队友/对面的框体设焦点就有点难受了。搞一组框体宏又太占按键...麦大有空给修复下呗

2，我记得菜单里有pvp环境下tab键只选中敌方玩家的功能，但是现在还是会tab到宠物、图腾等。麦大帮确认下，没有的话，我自己加个单体.

**Comment by Humwq** [comment]
哦  还有jjc使用的是团队的布局，队友框体略小，不太方便看指示器。
类似大米的小队布局应该更好点

**Comment by fafaraway** [comment]
1是故意的，如果可以对框体使用会影响点击施法的功能
2我好多年没玩过战场了，等我有空测试一下

**Comment by Humwq** [comment]
哦～这样啊 
可不可以有个选项，不用点击施法，然后可以对框体用快捷焦点呢

**Comment by fafaraway** [comment]
快速焦点现在可以直接对框体使用了，在控制面板里有开关
PVP环境的自动切换tab更新后应该正常了
