### ISSUE TITLE
自动成就截图好像失效了

### ISSUE THREAD

**Issue by Oo-Lucas-oO** [fafaraway/andromeda#81]
Emmm...最新的9.24好像成就截图失效了。好像之前我记得是更新里说明过所有角色第一次获得成就才会截图，重复的成就不会截图。但是这几天爬扭曲回廊，都是第一次获得成就，然后昨天打开截图文件夹发现1-6的成就截图一张也木有。。。不知道你有没有遇到这种情况啊麦大？？

**Comment by Humwq** [comment]
能用啊  
我10号还有自动截图的

**Comment by Humwq** [comment]
擦  是真的失效了。。。今天解锁名望23都没截图 ...

**Comment by fafaraway** [comment]
確實有問題，下個版本會修正。

**Comment by Oo-Lucas-oO** [comment]
> 確實有問題，下個版本會修正。

嗯呐等新版本了~😀
