### ISSUE TITLE
冷却字体修改

### ISSUE THREAD

**Issue by Oo-Lucas-oO** [fafaraway/andromeda#82]
Hi麦大，今天更新了9.25，这个动作图冷却计时变成跟热键一样的字体了。之前是这种单独的四方的字形，感觉还挺酷的。现在能在哪里改一下吗??NGA那个改字体的你回复楼层我看过了，好像跟这个没什么关系…主要之前一直没改过那里。看了下动作图下那个style文件，似乎跟9.24没什么区别…不知道怎么改一下…
![20210116_204122](https://user-images.githubusercontent.com/14848127/104812376-b2718c00-583c-11eb-8270-4f7d667e8d28.jpg)
就是这个图片一样。之前我自己放在wow目录下的font也没改动过。麻烦问下大佬可不可以从哪个文件改一下，谢谢~🙂

**Comment by fafaraway** [comment]
https://github.com/Solor/FreeUI/blob/Shadowlands/modules/cooldown/cooldown.lua#L31
`self.text:SetFont(C.Assets.Fonts.Bold, fontScale * FONT_SIZE, 'OUTLINE')`
这里就是控制冷却计时的字体设定，以前那个字体是 `C.Assets.Fonts.Square`

**Comment by Oo-Lucas-oO** [comment]
麦大一级棒~👍
