### ISSUE TITLE
Show cast spellname.

### ISSUE THREAD

**Issue by Smallinger** [fafaraway/andromeda#85]
Hey, i want to ask is it possible to show the spellname if a NPC or a Player Casting something ?

**Comment by fafaraway** [comment]
Not yet, but I can add it later.

**Comment by Smallinger** [comment]
Hey, thx something like this is enough.

![image](https://i.imgur.com/dh7nYzr.png)
The possibility to have it displayed below might also be interesting for people who prefer it that way.
It might be interesting to see the spellname in ne nameplate and Unitframe.

Befor i start a new issue, i ask here is it possible to create custom-filters for the bags and assigne items to the filters ?

![demo-image](https://i.imgur.com/fNHxhEZ.png)

i got this working with my own filterlisting writing in lua, i hope someday a function is there that you can use RightMouse button to create new filter and add items to them.

**Comment by fafaraway** [comment]
It's too complicated for me, I dont think I have enough time and energy to complete this 🙄
Alternatively, you may disable FreeUI's inventory module and use [cargBagsNivaya](https://www.wowinterface.com/downloads/info22329-cargBagsNivaya.html) instead.

**Comment by fafaraway** [comment]
9.3.3-beta has a new castbar module with spell name and time, try it.
