### ISSUE TITLE
CargBags Layout

### ISSUE THREAD

**Issue by datka1** [fafaraway/andromeda#9]
Hello. I am wonding is there any way to get FreeUI's Stand Alone Carbags addon with FreeUI;s Layout?

**Comment by fafaraway** [comment]
not sure what you mean, if you want to use old version cargBags_Nivaya, you can download it [here](https://github.com/Solor/FreeUI/tree/addd96946db6ab3cb6691627db8eb8dc0f9afdb4).

**Comment by datka1** [comment]
Hi. thanks for responce. How can i use https://imgur.com/a/6ffxdhp as a standalone addon? or how can i set this style to old cargbags nivaya ?

**Comment by fafaraway** [comment]
this is new built-in bag module, not cargBags_Nivaya.
you have to do some code work if you want to use it as a standalone addon.

**Comment by datka1** [comment]
Okey , Thank you very much, you can close the issue. 👍
